spring.application.name=IdentityCore
appname=IdentityCore

#Storage configuration
dbfilepath=config/DBConfig.cfg
cachefilepath=config/cache.cfg

#Notification service url
notification.service.url=http://localhost:8080/api/v1/notifications

#Jwt Configuration
security.jwt.issuer=https://identity.swiunflow.com
security.jwt.audience=swiunflow
security.jwt.expiration-seconds=900


# Swagger Configuration
springdoc.swagger-ui.enabled=true
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
